# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Building.create(name:'Adair')
Building.create(name:'Andrews')
Building.create(name:'Blow')
Building.create(name:'Bozarth')
Building.create(name:'Center for Archaeological Research')
Building.create(name:'Ceramics Studio')
Building.create(name:'Endocrinology Lab')
Building.create(name:'Ewell')
Building.create(name:'ISC1')
Building.create(name:'ISC2')
Building.create(name:'James Blair ')
Building.create(name:'Jones')
Building.create(name:'Keck')
Building.create(name:'Law School')
Building.create(name:'Matoaka Art Studio')
Building.create(name:'McGlothlin-Street Hall')
Building.create(name:'Miller')
Building.create(name:'Millington')
Building.create(name:'Morton')
Building.create(name:'PBK Hall')
Building.create(name:'Prince George House')
Building.create(name:'Small')
Building.create(name:'School Of Education')
Building.create(name:'Tucker')
Building.create(name:'Tyler')
Building.create(name:'Washington')
Building.create(name:'Wren')
Building.create(name:'Barrett')
Building.create(name:'Brown')
Building.create(name:'Bryan')
Building.create(name:'Cabell')
Building.create(name:'Camm')
Building.create(name:'Campus Center')
Building.create(name:'Chandler')
Building.create(name:'Commons Dining Hall')
Building.create(name:'Dawson')
Building.create(name:'Dinwiddie')
Building.create(name:'Dupont')
Building.create(name:'Fauquier')
Building.create(name:'Giles')
Building.create(name:'Gooch')
Building.create(name:'Graduate Housing Complex')
Building.create(name:'Harrison')
Building.create(name:'Hughes')
Building.create(name:'Hunt')
Building.create(name:'Jamestown North')
Building.create(name:'Jamestown South')
Building.create(name:'Jefferson')
Building.create(name:'Landrum')
Building.create(name:'Lodge 2')
Building.create(name:'Lodge 4')
Building.create(name:'Lodge 6')
Building.create(name:'Lodge 8')
Building.create(name:'Lodge 10')
Building.create(name:'Lodge 12')
Building.create(name:'Lodge 16')
Building.create(name:'Ludwell 1xx')
Building.create(name:'Ludwell 2xx')
Building.create(name:'Ludwell 3xx')
Building.create(name:'Ludwell 4xx')
Building.create(name:'Ludwell 5xx')
Building.create(name:'Ludwell 6xx')
Building.create(name:'Ludwell 7xx')
Building.create(name:'Madison')
Building.create(name:'Meridian Coffee House')
Building.create(name:'Monroe ')
Building.create(name:'Munford')
Building.create(name:'Nicholas')
Building.create(name:'Nicholson')
Building.create(name:'Old Dominion ')
Building.create(name:'Page')
Building.create(name:'Pleasants')
Building.create(name:'Preston')
Building.create(name:'Reves Hall')
Building.create(name:'Sadler Center')
Building.create(name:'Sorority House 1: KKG')
Building.create(name:'Sorority House 2: ACO')
Building.create(name:'Sorority House 3: CO')
Building.create(name:'Sorority House 4: DDD')
Building.create(name:'Sorority House 5: PBP')
Building.create(name:'Sorority House 6: KD')
Building.create(name:'Sorority House 7: DG')
Building.create(name:'Sorority House 8: PM')
Building.create(name:'Sorority House 9: KAT')
Building.create(name:'Sorority House 10: DST')
Building.create(name:'Sorority House 11: GPB')
Building.create(name:'Sorority House 12: DP)')
Building.create(name:'Spotswood')
Building.create(name:'Stith')
Building.create(name:'Taliaferro')
Building.create(name:'Tazewell')
Building.create(name:'Tribe Square')
Building.create(name:'Green and Gold Village Griffin Halls (A-E)')
Building.create(name:'Green and Gold Village Eagle Halls (F-J)')
Building.create(name:'Green and Gold Village Lion Halls (K-M)')
Building.create(name:'Yates')
Building.create(name:'One Tribe Place')
Building.create(name:'Fraternity House 620 (KS)')
Building.create(name:'Fraternity House 630 (KA)')
Building.create(name:'Fraternity House 640 (ATO)')
Building.create(name:'Fraternity House 650')
Building.create(name:'Fraternity House 660 (DC)')
Building.create(name:'Fraternity House 670 (SP)')
Building.create(name:'Fraternity House 710')
Building.create(name:'Fraternity House 720 (SC)')
Building.create(name:'Fraternity House 730 (DP)')
Building.create(name:'Fraternity House 740 (BTP)')
Building.create(name:'Fraternity House 750 (KDR)')
Building.create(name:'Fraternity House 760')


